In [19]:
#bring in the prerequisites

import pandas as pd
import glob
import json
import numpy as np
import pandas as pd

In [20]:
# identify the folder where the files are -- this will be done once per team, aligning the team folder name to the column we will create
files = glob.glob('raw_tweets/pride_whitesox/*')
#files = glob.glob('user/*')
len(files)

192

In [21]:
#make a list to hold the files we are going to read
#then read the files into a dictionary

dictlist = []

for file in files:
    json_string = open(file, 'r').read()
    json_dict = json.loads(json_string)
    dictlist.append(json_dict)

In [22]:
#create a dataframe from the dictionary
df = pd.DataFrame(dictlist)
df.head()

,ID,datetime,has_media,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,text,url,user_id,usernameTweet
0,1164182907981914113,2019-08-21 10:30:09,NaN,False,False,NaN,179,14,29,Join us for Pride Night at #TheK on Septemb...,/Royals/status/1164182907981914113,28603812,Royals
1,1164188556128071682,2019-08-21 10:52:36,NaN,True,False,NaN,16,2,0,So glad the @Royals are finally promoting #Pr...,/RevJeffLukens/status/1164188556128071682,82402389,RevJeffLukens
2,1169382298984341504,2019-09-04 18:50:40,NaN,False,False,NaN,1,0,0,@ Royals Pride Night at The K #kcroyals #p...,/short4cute/status/1169382298984341504,538611232,short4cute
3,1169388554977533952,2019-09-04 19:15:32,NaN,False,False,NaN,2,0,0,Tonight @Royals are holding their first ever ...,/DaveDMarko/status/1169388554977533952,239334748,DaveDMarko
4,1169393795416436736,2019-09-04 19:36:21,NaN,False,False,NaN,6,1,0,Just out here being my self for Pride Night ...,/Lieano/status/1169393795416436736,90693778,Lieano

In [23]:
#create the new column and give all rows the same value-- this is how we will keep track of the team names
df['team'] = "whitesox"
df.head()

,ID,datetime,has_media,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,text,url,user_id,usernameTweet,team
0,1164182907981914113,2019-08-21 10:30:09,NaN,False,False,NaN,179,14,29,Join us for Pride Night at #TheK on Septemb...,/Royals/status/1164182907981914113,28603812,Royals,royals
1,1164188556128071682,2019-08-21 10:52:36,NaN,True,False,NaN,16,2,0,So glad the @Royals are finally promoting #Pr...,/RevJeffLukens/status/1164188556128071682,82402389,RevJeffLukens,royals
2,1169382298984341504,2019-09-04 18:50:40,NaN,False,False,NaN,1,0,0,@ Royals Pride Night at The K #kcroyals #p...,/short4cute/status/1169382298984341504,538611232,short4cute,royals
3,1169388554977533952,2019-09-04 19:15:32,NaN,False,False,NaN,2,0,0,Tonight @Royals are holding their first ever ...,/DaveDMarko/status/1169388554977533952,239334748,DaveDMarko,royals
4,1169393795416436736,2019-09-04 19:36:21,NaN,False,False,NaN,6,1,0,Just out here being my self for Pride Night ...,/Lieano/status/1169393795416436736,90693778,Lieano,royals

In [24]:
#dump it to a csv so we can use it later

df.to_csv('basic_csv/royals_tweets.csv', index=True)